{{- if .Values.ocp.enabled }}
{{- if .Values.ocp.routes.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: api
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "ez-platform.labels" . | nindent 4 }}
    app: datasource-management
spec:
  host: api.{{ .Values.ocp.domain }}
  to:
    kind: Service
    name: datasource-management
    weight: 100
  port:
    targetPort: 5001
  tls:
    termination: {{ .Values.ocp.routes.tls.termination }}
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
{{- end }}
{{- end }}
