"""
Comprehensive Clone Datasource Test Suite
Generated by webapp-testing skill

Tests all clone feature scenarios including edge cases:
- Action button visibility and tooltips
- Clone from list page (modal, navigation, form pre-fill)
- Clone from details page
- Clone uniqueness (multiple clones of same datasource)
- Delete popconfirm functionality
- Duplicate name error handling
- Form field validation after clone
"""
import sys, io, re, time
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')
from playwright.sync_api import sync_playwright

BASE_URL = 'http://172.30.22.206:32608'
RESULTS = []

def report(test_name, passed, detail=""):
    status = "✓ PASS" if passed else "✗ FAIL"
    RESULTS.append((test_name, passed, detail))
    print(f"  {status}: {test_name}" + (f" — {detail}" if detail else ""))

def wait_for_table(page):
    page.goto(f'{BASE_URL}/datasources')
    page.wait_for_selector('.ant-table-tbody tr', timeout=30000)
    page.wait_for_timeout(2000)

with sync_playwright() as p:
    browser = p.chromium.launch(headless=True)
    page = browser.new_page(viewport={"width": 1400, "height": 900})

    print("=" * 60)
    print(" CLONE DATASOURCE — COMPREHENSIVE TEST SUITE")
    print("=" * 60)

    # ========================================
    # TEST GROUP 1: Action Buttons Layout
    # ========================================
    print("\n--- Group 1: Action Buttons Layout ---")

    wait_for_table(page)
    first_row = page.locator('.ant-table-tbody tr').first

    # T1.1: All 5 icon buttons present
    icons = ['eye', 'edit', 'copy', 'thunderbolt', 'delete']
    all_visible = True
    for icon in icons:
        visible = first_row.locator(f'.anticon-{icon}').is_visible()
        if not visible:
            all_visible = False
    report("T1.1 All 5 action icon buttons visible", all_visible, f"Icons: {icons}")

    # T1.2: Buttons are icon-only (no text labels)
    buttons = first_row.locator('button').all()
    # Last 5 buttons should be action buttons (some rows may have status select)
    action_btns = [b for b in buttons if any(
        b.locator(f'.anticon-{i}').count() > 0 for i in icons
    )]
    all_icon_only = all(btn.text_content().strip() == '' for btn in action_btns)
    report("T1.2 Action buttons are icon-only (no text)", all_icon_only)

    # T1.3: Tooltips appear on hover
    copy_btn = first_row.locator('button .anticon-copy').locator('..')
    copy_btn.hover()
    page.wait_for_timeout(500)
    tooltip = page.locator('.ant-tooltip-inner')
    tooltip_visible = tooltip.is_visible()
    tooltip_text = tooltip.text_content() if tooltip_visible else ""
    report("T1.3 Clone button has tooltip on hover", tooltip_visible, f"Tooltip: '{tooltip_text}'")

    # ========================================
    # TEST GROUP 2: Clone from List Page
    # ========================================
    print("\n--- Group 2: Clone from List Page ---")

    wait_for_table(page)
    first_row = page.locator('.ant-table-tbody tr').first

    # Get original datasource name
    orig_name_el = first_row.locator('td').nth(1).locator('div').first
    orig_name = orig_name_el.text_content().strip() if orig_name_el.is_visible() else "unknown"

    # T2.1: Clone button click shows confirmation modal
    clone_btn = first_row.locator('button .anticon-copy').locator('..')
    clone_btn.click()
    page.wait_for_timeout(3000)

    modal = page.locator('.ant-modal-confirm')
    modal_visible = modal.is_visible()
    report("T2.1 Clone shows confirmation modal", modal_visible)

    if modal_visible:
        # T2.2: Modal has correct content
        modal_title = modal.locator('.ant-modal-confirm-title').text_content()
        modal_body = modal.locator('.ant-modal-confirm-content').text_content()
        has_title = 'שכפול' in modal_title
        has_name = orig_name in modal_body if orig_name != "unknown" else True
        has_schedule_note = 'תזמון' in modal_body or 'יושבת' in modal_body
        report("T2.2 Modal title says 'שכפול'", has_title, f"Title: '{modal_title}'")
        report("T2.3 Modal mentions datasource name", has_name)
        report("T2.4 Modal mentions schedule will be disabled", has_schedule_note)

        # T2.5: Cancel returns to list
        modal.locator('.ant-btn:not(.ant-btn-primary)').click()
        page.wait_for_timeout(500)
        report("T2.5 Cancel stays on list page", '/datasources' in page.url and '/new' not in page.url)

        # T2.6: Confirm navigates to create form
        clone_btn = page.locator('.ant-table-tbody tr').first.locator('button .anticon-copy').locator('..')
        clone_btn.click()
        page.wait_for_timeout(3000)
        modal = page.locator('.ant-modal-confirm')
        modal.locator('.ant-btn-primary').click()
        page.wait_for_timeout(3000)
        report("T2.6 Confirm navigates to /datasources/new", '/datasources/new' in page.url, f"URL: {page.url}")

        # T2.7: Form title indicates cloning
        page_title = page.locator('h2').first.text_content() if page.locator('h2').first.is_visible() else ""
        report("T2.7 Form title says 'שכפול מקור נתונים'", 'שכפול' in page_title, f"Title: '{page_title}'")

        # T2.8: Name is prefixed with unique suffix
        name_input = page.locator('input#name')
        if name_input.is_visible():
            name_val = name_input.input_value()
            has_prefix = name_val.startswith('העתק של') or name_val.startswith('Copy of')
            has_suffix = bool(re.search(r'\([a-z0-9]{5}\)$', name_val))
            report("T2.8 Name prefixed with 'העתק של'", has_prefix, f"Name: '{name_val}'")
            report("T2.9 Name has random 5-char suffix", has_suffix, f"Name: '{name_val}'")
        else:
            report("T2.8 Name field visible", False, "input#name not found")
            report("T2.9 Name has suffix", False, "skipped")

        # T2.10: Supplier field is populated
        supplier_input = page.locator('input#supplierName')
        if supplier_input.is_visible():
            supplier_val = supplier_input.input_value()
            report("T2.10 Supplier field populated", len(supplier_val) > 0, f"Supplier: '{supplier_val}'")
        else:
            report("T2.10 Supplier field visible", False)

        # T2.11: Retention days populated
        retention_input = page.locator('input#retentionDays')
        if retention_input.is_visible():
            ret_val = retention_input.input_value()
            report("T2.11 Retention days populated", len(ret_val) > 0, f"Value: '{ret_val}'")
        else:
            report("T2.11 Retention days visible", False)

    page.screenshot(path='test-results/webapp-clone-form.png')

    # ========================================
    # TEST GROUP 3: Clone from Details Page
    # ========================================
    print("\n--- Group 3: Clone from Details Page ---")

    wait_for_table(page)
    first_row = page.locator('.ant-table-tbody tr').first
    view_btn = first_row.locator('button .anticon-eye').locator('..')
    view_btn.click()
    page.wait_for_url(re.compile(r'/datasources/[a-f0-9]+$'), timeout=15000)
    page.wait_for_timeout(3000)

    # T3.1: Clone button visible on details page
    details_clone = page.locator('button .anticon-copy').locator('..')
    report("T3.1 Clone button visible on details page", details_clone.is_visible())

    # T3.2: Clone from details shows modal
    if details_clone.is_visible():
        details_clone.click()
        page.wait_for_timeout(3000)
        modal3 = page.locator('.ant-modal-confirm')
        report("T3.2 Details clone shows modal", modal3.is_visible())

        if modal3.is_visible():
            # T3.3: Confirm navigates to form
            modal3.locator('.ant-btn-primary').click()
            page.wait_for_timeout(3000)
            report("T3.3 Details clone navigates to /new", '/datasources/new' in page.url)

    page.screenshot(path='test-results/webapp-details-clone.png')

    # ========================================
    # TEST GROUP 4: Clone Uniqueness
    # ========================================
    print("\n--- Group 4: Clone Uniqueness ---")

    # Clone the same datasource twice and verify different names
    names = []
    for i in range(2):
        wait_for_table(page)
        first_row = page.locator('.ant-table-tbody tr').first
        clone_btn = first_row.locator('button .anticon-copy').locator('..')
        clone_btn.click()
        page.wait_for_timeout(3000)
        modal = page.locator('.ant-modal-confirm')
        if modal.is_visible():
            modal.locator('.ant-btn-primary').click()
            page.wait_for_timeout(3000)
            name_input = page.locator('input#name')
            if name_input.is_visible():
                names.append(name_input.input_value())

    if len(names) == 2:
        report("T4.1 Two clones have different names", names[0] != names[1], f"'{names[0]}' vs '{names[1]}'")
    else:
        report("T4.1 Two clones have different names", False, f"Only got {len(names)} names")

    # ========================================
    # TEST GROUP 5: Delete Action
    # ========================================
    print("\n--- Group 5: Delete Action ---")

    wait_for_table(page)
    first_row = page.locator('.ant-table-tbody tr').first

    # T5.1: Delete shows popconfirm
    delete_btn = first_row.locator('button .anticon-delete').locator('..')
    delete_btn.click()
    page.wait_for_timeout(1000)
    popconfirm = page.locator('.ant-popconfirm, .ant-popover')
    report("T5.1 Delete shows popconfirm", popconfirm.is_visible())

    # T5.2: Escape cancels
    if popconfirm.is_visible():
        page.keyboard.press('Escape')
        page.wait_for_timeout(500)
        report("T5.2 Escape cancels popconfirm", not popconfirm.is_visible())

    page.screenshot(path='test-results/webapp-delete.png')

    # ========================================
    # FINAL REPORT
    # ========================================
    browser.close()

    print("\n" + "=" * 60)
    print(" TEST RESULTS SUMMARY")
    print("=" * 60)

    passed = sum(1 for _, p, _ in RESULTS if p)
    failed = sum(1 for _, p, _ in RESULTS if not p)
    total = len(RESULTS)

    for name, p, detail in RESULTS:
        status = "✓" if p else "✗"
        print(f"  {status} {name}")

    print(f"\n  Total: {total} | Passed: {passed} | Failed: {failed}")
    print(f"  Pass rate: {passed/total*100:.0f}%")
    print("=" * 60)

    if failed > 0:
        sys.exit(1)
