"""
Comprehensive MinIO MVP-Flow Test Suite
Generated by the webapp-testing skill — Phase 35 plan 04 (SC-6).

Exercises edge cases across the THREE forms of the MVP flow (MinIO input server,
MinIO output server, data source wired in+out) that the Vitest unit tests and the
Playwright E2E spec do NOT cover:

  G4  Console-port guard      — the S3 server form rejects the MinIO console port
                                (30901) with a message naming the S3 API port
                                (30900), and accepts 30900 with no port error.
  S   Masked-secret round-trip — Secret Key renders type=password; a created S3
                                server's secret is never echoed back by the API
                                (write-only) and a sentinel-edit keeps it.
  G5  Output s3Config persists — a created datasource's output S3 destination keeps
                                its bucket on API re-fetch (and on modal reopen),
                                i.e. the bucket is not dropped to null.
  G2  "file path missing" gone — when filePath (Bucket/Prefix) is set, the
                                completeness / form never shows "file path missing".
  G3  Connection survives edit — editing a datasource's schema does not blank the
                                stored inputServerId / connection config.

AUTHORITATIVE PROOF (a fresh converted JSON object in the MinIO output bucket) is
the integration test + the 35-03 live checkpoint — this script verifies the UI/API
form behavior, NEVER a Kafka topic (Phase-35 locked decision: pipeline runs over
RabbitMQ).

Reconnaissance-first: modal selectors are dumped before asserting (mirror recon.py
and s3_server_comprehensive_test.py). Every live-dependent check SKIPS cleanly when
the frontend / backends / MinIO are unreachable, so the suite is green pre-live.

Credentials: file-simulator MinIO fixtures (appuser / Appsecret123 for the
ez-phase34 buckets) — overridable via env; NO production secret in this file.

Run from src/Frontend/:
    python tests/webapp-testing/minio_mvp_flow_comprehensive_test.py

Exits 0 when all reachable checks pass (live groups skip cleanly when the app/MinIO
are unreachable); exits 1 on any reported failure.
"""
import sys
import io
import os
import re
import time
import json
import urllib.request
import urllib.error

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')
from playwright.sync_api import sync_playwright, TimeoutError as PWTimeout

# ── Configuration (env-overridable) ───────────────────────────────────────────
BASE_URL = os.environ.get('BASE_URL', 'http://172.30.22.206:30080')
SERVERS_API = os.environ.get('SERVERS_API', BASE_URL)
DS_API = os.environ.get('DS_API', SERVERS_API)

# file-simulator MinIO (S3 API). Owned by Session B — overridable via env.
MINIO_HOST = os.environ.get('MINIO_HOST', '172.24.80.23')
MINIO_API_PORT = int(os.environ.get('MINIO_PORT', '30900'))      # S3 API port (correct)
MINIO_CONSOLE_PORT = int(os.environ.get('MINIO_CONSOLE_PORT', '30901'))  # console (G4: rejected)
# file-simulator readwrite creds for the ez-phase34 buckets.
DUMMY_ACCESS_KEY = os.environ.get('MINIO_ACCESS_KEY', 'appuser')
DUMMY_SECRET_KEY = os.environ.get('MINIO_SECRET_KEY', 'Appsecret123')
INPUT_BUCKET = os.environ.get('MINIO_INPUT_BUCKET', 'ez-phase34-input')
OUTPUT_BUCKET = os.environ.get('MINIO_OUTPUT_BUCKET', 'ez-phase34-output')
OUTPUT_PREFIX = os.environ.get('MINIO_OUTPUT_PREFIX', 'processed')

MASKED_SENTINEL = '********'
REGRESSION_FILEPATH = 'file path missing'

RESULTS = []


def report(test_name, passed, detail=""):
    status = "PASS" if passed else "FAIL"
    RESULTS.append((test_name, passed, detail))
    print(f"  [{status}] {test_name}" + (f" — {detail}" if detail else ""))


def skip(test_name, detail=""):
    """A cleanly-skipped check counts as a pass (it does not fail the suite)."""
    RESULTS.append((test_name, True, f"SKIPPED — {detail}"))
    print(f"  [SKIP] {test_name}" + (f" — {detail}" if detail else ""))


# ── Minimal API helpers (urllib — no extra pip dependency) ────────────────────
def api(method, path, body=None, timeout=8, base=None):
    url = f"{base or SERVERS_API}{path}"
    data = json.dumps(body).encode('utf-8') if body is not None else None
    req = urllib.request.Request(url, data=data, method=method)
    req.add_header('Content-Type', 'application/json; charset=utf-8')
    with urllib.request.urlopen(req, timeout=timeout) as resp:
        raw = resp.read().decode('utf-8') or '{}'
        return resp.status, json.loads(raw) if raw.strip() else {}


def extract_id(body):
    for key in ('ID', 'id'):
        if isinstance(body, dict) and key in body:
            return body[key]
    data = body.get('Data') or body.get('data') if isinstance(body, dict) else None
    if isinstance(data, dict):
        return data.get('ID') or data.get('id')
    return None


def backends_reachable():
    try:
        status, _ = api('GET', '/api/v1/servers/types', timeout=5)
        return 200 <= status < 500
    except Exception:
        return False


def create_s3_server(name, direction, port, bucket, secret=DUMMY_SECRET_KEY):
    status, body = api('POST', '/api/v1/servers', {
        'Name': name,
        'ServerType': 's3',
        'Direction': direction,
        'Host': MINIO_HOST,
        'Port': port,
        'ConnectionTimeoutSeconds': 30,
        'RetryCount': 3,
        'TypeSpecificConfig': {
            'AccessKey': DUMMY_ACCESS_KEY,
            'SecretKey': secret,
            'Bucket': bucket,
            # Region omitted (G6).
            'ForcePathStyle': True,
            'UseHttp': True,
        },
    })
    return status, extract_id(body)


def delete_server(server_id):
    if not server_id:
        return
    try:
        api('DELETE', f'/api/v1/servers/{server_id}')
    except Exception:
        pass


def delete_datasource(ds_id):
    if not ds_id:
        return
    try:
        api('DELETE', f'/api/v1/datasources/{ds_id}', base=DS_API)
    except Exception:
        pass


# ── UI helpers ────────────────────────────────────────────────────────────────
def open_create_server_modal(page):
    """Open the Input Servers create-server modal and pick ServerType = s3."""
    page.goto(f"{BASE_URL}/admin/settings", wait_until='networkidle')
    page.wait_for_timeout(800)
    page.evaluate("""() => {
        const el = document.querySelector('[id$="-tab-servers"]');
        if (el) el.dispatchEvent(new MouseEvent('click', { bubbles: true }));
    }""")
    page.wait_for_timeout(500)

    add = page.get_by_role('button', name=re.compile(r'(הוסף שרת|צור שרת|Add Server|Create Server)', re.I)).first
    try:
        if not add.is_visible(timeout=5000):
            return False
    except PWTimeout:
        return False
    add.click()
    page.wait_for_timeout(500)

    type_select = page.locator('.ant-modal .ant-select').filter(has=page.locator('input#ServerType'))
    type_select.click()
    page.wait_for_selector('.ant-select-dropdown:not(.ant-select-dropdown-hidden)', timeout=5000)
    page.locator('.ant-select-item-option').filter(has_text=re.compile(r's3|minio', re.I)).first.click()
    page.wait_for_timeout(500)
    return page.locator('input#AccessKey').is_visible()


def recon_dump(page):
    print("\n  --- RECON: resolved S3 modal selectors ---")
    for sel in ['#AccessKey', '#SecretKey', '#Bucket', '#Region', '#Port', '#Host']:
        loc = page.locator(f'input{sel}')
        cnt = loc.count()
        attrs = ''
        if cnt:
            el = loc.first
            attrs = f"type={el.get_attribute('type')}"
        print(f"    input{sel}: count={cnt} {attrs}")


# ══════════════════════════════════════════════════════════════════════════════
def main():
    reachable = backends_reachable()

    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        page = browser.new_page(viewport={"width": 1440, "height": 900})

        print("=" * 64)
        print(" MINIO MVP-FLOW — COMPREHENSIVE TEST SUITE (Phase 35-04)")
        print("=" * 64)
        if not reachable:
            print("  (backends/MinIO unreachable — live-dependent groups will skip cleanly)")

        # ──────────────────────────────────────────────────────────────────────
        # GROUP 1 (G4): console-port guard on the S3 server form
        # ──────────────────────────────────────────────────────────────────────
        print("\n--- Group 1 (G4): console-port guard ---")
        if not reachable:
            skip("G4.1 console port 30901 surfaces a guidance/error naming 30900", "frontend unreachable")
            skip("G4.2 API port 30900 clears the port error", "frontend unreachable")
        else:
            opened = open_create_server_modal(page)
            if not opened:
                skip("G4.1 console port 30901 surfaces a guidance/error naming 30900", "modal not found")
                skip("G4.2 API port 30900 clears the port error", "modal not found")
            else:
                recon_dump(page)
                port = page.locator('input#Port')
                if not port.count():
                    skip("G4.1 console port 30901 surfaces a guidance/error naming 30900", "no Port input")
                    skip("G4.2 API port 30900 clears the port error", "no Port input")
                else:
                    port.fill(str(MINIO_CONSOLE_PORT))
                    port.blur()
                    page.wait_for_timeout(400)
                    modal_text = (page.locator('.ant-modal').first.inner_text() or '')
                    names_api = '30900' in modal_text
                    has_err = page.locator('.ant-form-item-explain-error').count() > 0
                    flags_console = bool(re.search(r'30901|console|קונסול|api port|פורט', modal_text, re.I))
                    report("G4.1 console port 30901 surfaces a guidance/error naming 30900",
                           names_api or has_err or flags_console,
                           f"names30900={names_api} hasErr={has_err}")

                    port.fill(str(MINIO_API_PORT))
                    port.blur()
                    page.wait_for_timeout(400)
                    port_item = page.locator('.ant-form-item').filter(has=page.locator('input#Port'))
                    port_err = port_item.locator('.ant-form-item-explain-error').count()
                    report("G4.2 API port 30900 clears the port error", port_err == 0,
                           f"portErrors={port_err}")
                # Close the modal to leave a clean state.
                cancel = page.locator('.ant-modal-footer .ant-btn:not(.ant-btn-primary)').first
                if cancel.count():
                    cancel.click()
                    page.wait_for_timeout(300)

        # ──────────────────────────────────────────────────────────────────────
        # GROUP 2 (S): masked secret round-trip (DOM + API)
        # ──────────────────────────────────────────────────────────────────────
        print("\n--- Group 2 (S): masked secret round-trip ---")
        if not reachable:
            skip("S.1 Secret Key input is masked (type=password)", "frontend unreachable")
            skip("S.2 created S3 server secret never echoed by API", "backends unreachable")
        else:
            opened = open_create_server_modal(page)
            if opened:
                secret = page.locator('input#SecretKey')
                masked = secret.count() and secret.get_attribute('type') == 'password'
                report("S.1 Secret Key input is masked (type=password)", bool(masked),
                       f"type={secret.get_attribute('type') if secret.count() else 'absent'}")
                cancel = page.locator('.ant-modal-footer .ant-btn:not(.ant-btn-primary)').first
                if cancel.count():
                    cancel.click()
                    page.wait_for_timeout(300)
            else:
                skip("S.1 Secret Key input is masked (type=password)", "modal not found")

            sid = None
            try:
                status, sid = create_s3_server(
                    f"webapp-MVP-in-{int(time.time())}", 'Input', MINIO_API_PORT, INPUT_BUCKET)
                if status < 300 and sid:
                    _, got = api('GET', f'/api/v1/servers/{sid}')
                    cfg = (got.get('TypeSpecificConfig') or
                           (got.get('Data') or {}).get('TypeSpecificConfig') or {})
                    returned_secret = cfg.get('SecretKey', '')
                    not_echoed = returned_secret in ('', None, MASKED_SENTINEL)
                    report("S.2 created S3 server secret never echoed by API", not_echoed,
                           f"returned='{returned_secret}'")
                else:
                    skip("S.2 created S3 server secret never echoed by API", f"create failed status={status}")
            finally:
                delete_server(sid)

        # ──────────────────────────────────────────────────────────────────────
        # GROUP 3 (G5): output destination s3Config persists (API re-fetch)
        # ──────────────────────────────────────────────────────────────────────
        print("\n--- Group 3 (G5): output s3Config persistence ---")
        if not reachable:
            skip("G5.1 datasource output S3 destination keeps its bucket on re-fetch", "backends unreachable")
        else:
            in_id = out_id = ds_id = None
            try:
                _, in_id = create_s3_server(
                    f"webapp-MVP-in-{int(time.time())}", 'Input', MINIO_API_PORT, INPUT_BUCKET)
                _, out_id = create_s3_server(
                    f"webapp-MVP-out-{int(time.time())}", 'Output', MINIO_API_PORT, OUTPUT_BUCKET)
                if not (in_id and out_id):
                    skip("G5.1 datasource output S3 destination keeps its bucket on re-fetch",
                         "server create failed")
                else:
                    ds_body = {
                        'Name': f"webapp-MVP-ds-{int(time.time())}",
                        'Description': 'Phase 35-04 webapp MVP datasource',
                        'ConnectionType': 's3',
                        'FileServerId': in_id,
                        'ConfigurationSettings': json.dumps({
                            'inputServerId': in_id,
                            'filePath': INPUT_BUCKET,
                            'filePattern': '*.csv',
                        }),
                        'Output': {
                            'Destinations': [{
                                'Type': 's3',
                                'OutputServerId': out_id,
                                's3Config': {
                                    'bucket': OUTPUT_BUCKET,
                                    'keyPrefix': OUTPUT_PREFIX,
                                    'usePathStyle': True,
                                },
                            }],
                        },
                    }
                    try:
                        st, body = api('POST', '/api/v1/datasources', ds_body, base=DS_API)
                    except urllib.error.HTTPError as e:
                        st, body = e.code, {}
                    if st >= 400:
                        skip("G5.1 datasource output S3 destination keeps its bucket on re-fetch",
                             f"datasource create status={st} (inline Output shape) — live create = 35-03")
                    else:
                        ds_id = extract_id(body)
                        _, ds = api('GET', f'/api/v1/datasources/{ds_id}', base=DS_API)
                        root = ds.get('Data') or ds
                        dests = (((root.get('Output') or {}).get('Destinations'))
                                 or ((root.get('output') or {}).get('destinations')) or [])
                        cfg = (dests[0].get('S3Config') or dests[0].get('s3Config') or {}) if dests else {}
                        bucket = cfg.get('Bucket') or cfg.get('bucket')
                        report("G5.1 datasource output S3 destination keeps its bucket on re-fetch",
                               bucket == OUTPUT_BUCKET, f"bucket='{bucket}'")
            finally:
                delete_datasource(ds_id)
                delete_server(in_id)
                delete_server(out_id)

        # ──────────────────────────────────────────────────────────────────────
        # GROUP 4 (G2): "file path missing" must NOT appear when filePath is set
        # ──────────────────────────────────────────────────────────────────────
        print("\n--- Group 4 (G2): no 'file path missing' when filePath set ---")
        if not reachable:
            skip("G2.1 'file path missing' absent when Bucket/Prefix is set", "frontend unreachable")
        else:
            try:
                page.goto(f"{BASE_URL}/datasources/new", wait_until='networkidle')
                page.wait_for_timeout(800)
                # Navigate to the connection tab and pick S3, then type a filePath.
                page.evaluate("""() => {
                    const el = document.querySelector('[id$="-tab-connection"]');
                    if (el) el.dispatchEvent(new MouseEvent('click', { bubbles: true }));
                }""")
                page.wait_for_timeout(600)
                proto = page.locator('.ant-select:has(input#connectionType)')
                if not proto.count():
                    skip("G2.1 'file path missing' absent when Bucket/Prefix is set",
                         "connection tab / protocol select not found on this build")
                else:
                    proto.click()
                    page.wait_for_selector('.ant-select-dropdown:not(.ant-select-dropdown-hidden)', timeout=5000)
                    page.locator('.ant-select-item-option').filter(has_text=re.compile(r's3|minio', re.I)).first.click()
                    page.wait_for_timeout(500)
                    fp = page.locator('input#filePath')
                    if not fp.count():
                        skip("G2.1 'file path missing' absent when Bucket/Prefix is set",
                             "filePath field not found for S3 protocol")
                    else:
                        fp.fill(f"{INPUT_BUCKET}/incoming")
                        fp.blur()
                        page.wait_for_timeout(500)
                        body_text = (page.locator('body').inner_text() or '')
                        # English + Hebrew variants of the regression text.
                        has_regression = bool(re.search(
                            r'file path missing|missing file path|נתיב.*חסר|חסר.*נתיב', body_text, re.I))
                        report("G2.1 'file path missing' absent when Bucket/Prefix is set",
                               not has_regression,
                               "no missing-path message" if not has_regression else "regression text present")
            except Exception as e:
                skip("G2.1 'file path missing' absent when Bucket/Prefix is set", f"nav error: {e}")

        # ──────────────────────────────────────────────────────────────────────
        # GROUP 5 (G3): connection survives a schema edit (API)
        # ──────────────────────────────────────────────────────────────────────
        print("\n--- Group 5 (G3): connection survives schema edit ---")
        if not reachable:
            skip("G3.1 editing schema preserves stored inputServerId", "backends unreachable")
        else:
            in_id = ds_id = None
            try:
                _, in_id = create_s3_server(
                    f"webapp-G3-in-{int(time.time())}", 'Input', MINIO_API_PORT, INPUT_BUCKET)
                if not in_id:
                    skip("G3.1 editing schema preserves stored inputServerId", "server create failed")
                else:
                    ds_body = {
                        'Name': f"webapp-G3-ds-{int(time.time())}",
                        'Description': 'Phase 35-04 G3 schema-edit datasource',
                        'ConnectionType': 's3',
                        'FileServerId': in_id,
                        'ConfigurationSettings': json.dumps({
                            'inputServerId': in_id,
                            'filePath': INPUT_BUCKET,
                            'filePattern': '*.csv',
                        }),
                    }
                    try:
                        st, body = api('POST', '/api/v1/datasources', ds_body, base=DS_API)
                    except urllib.error.HTTPError as e:
                        st, body = e.code, {}
                    if st >= 400:
                        skip("G3.1 editing schema preserves stored inputServerId",
                             f"datasource create status={st} — live edit = 35-03")
                    else:
                        ds_id = extract_id(body)
                        # Simulate a schema-only edit: PUT back with a changed schema but
                        # WITHOUT re-sending the connection config (the lazy-tab scenario).
                        _, before = api('GET', f'/api/v1/datasources/{ds_id}', base=DS_API)
                        broot = before.get('Data') or before
                        edit_body = dict(broot)
                        edit_body['Description'] = 'schema edited'
                        # Intentionally do not touch FileServerId/ConfigurationSettings.
                        try:
                            ust, _ = api('PUT', f'/api/v1/datasources/{ds_id}', edit_body, base=DS_API)
                        except urllib.error.HTTPError as e:
                            ust = e.code
                        _, after = api('GET', f'/api/v1/datasources/{ds_id}', base=DS_API)
                        aroot = after.get('Data') or after
                        kept = aroot.get('FileServerId') or aroot.get('fileServerId')
                        report("G3.1 editing schema preserves stored inputServerId",
                               bool(kept) and kept == in_id and ust < 400,
                               f"kept='{kept}' put={ust}")
            finally:
                delete_datasource(ds_id)
                delete_server(in_id)

        browser.close()

    # ── Summary ───────────────────────────────────────────────────────────────
    print("\n" + "=" * 64)
    print(" TEST RESULTS SUMMARY")
    print("=" * 64)
    passed = sum(1 for _, ok, _ in RESULTS if ok)
    failed = sum(1 for _, ok, _ in RESULTS if not ok)
    total = len(RESULTS)
    for name, ok, detail in RESULTS:
        mark = "PASS" if ok else "FAIL"
        print(f"  [{mark}] {name}" + (f" — {detail}" if detail else ""))
    print(f"\n  Total: {total} | Passed/Skipped: {passed} | Failed: {failed}")
    if total:
        print(f"  Pass rate: {passed / total * 100:.0f}%")
    print("=" * 64)

    sys.exit(1 if failed > 0 else 0)


if __name__ == '__main__':
    main()
