"""
Comprehensive S3 / MinIO Server Form Test Suite
Generated by the webapp-testing skill — Phase 34 plan 05.

Covers the masked-credential edge cases that the Vitest unit test and the
Playwright E2E spec do NOT exercise:

  T1 Secret masking (DOM)        — Secret Key renders type=password; the typed
                                   secret is absent from every plaintext attribute.
  T2 Edit keeps stored secret    — editing with a blank/sentinel Secret Key field
                                   preserves the stored secret (API re-fetch; no
                                   empty overwrite).
  T3 Cancel discards credentials — typing Access/Secret then Cancel leaves no
                                   leaked state when the modal is reopened.
  T4 Test-Connection messaging   — success path shows success; failure path shows
                                   a clear error and NEVER "IAM credentials is
                                   missing" (gated to skip when MinIO/backends down).
  T5 Tooltip/help coverage       — the new S3 field labels surface help text.

Reconnaissance-first: the modal selectors are dumped before asserting so the
suite binds to the real DOM (mirror recon.py).

Credentials: throwaway public MinIO fixtures (minioadmin / minioadmin123) — NO
production secret appears in this file (mitigates T-34-14).

Run from src/Frontend/:
    python tests/webapp-testing/s3_server_comprehensive_test.py

Exits 0 when all reachable checks pass (live Test-Connection success-path skipped
cleanly if MinIO/backends are unreachable); exits 1 on any reported failure.
"""
import sys
import io
import os
import re
import time
import json
import urllib.request
import urllib.error

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')
from playwright.sync_api import sync_playwright, TimeoutError as PWTimeout

# ── Configuration (env-overridable) ───────────────────────────────────────────
BASE_URL = os.environ.get('BASE_URL', 'http://172.30.22.206:30080')
SERVERS_API = os.environ.get('SERVERS_API', BASE_URL)

MINIO_HOST = os.environ.get('MINIO_HOST', '172.24.80.23')
MINIO_PORT = int(os.environ.get('MINIO_PORT', '30900'))
# Throwaway public MinIO fixtures — never a production secret.
DUMMY_ACCESS_KEY = os.environ.get('MINIO_ACCESS_KEY', 'minioadmin')
DUMMY_SECRET_KEY = os.environ.get('MINIO_SECRET_KEY', 'minioadmin123')
DUMMY_BUCKET = os.environ.get('MINIO_BUCKET', 'test-bucket')

MASKED_SENTINEL = '********'
REGRESSION_STRING = 'IAM credentials is missing'

RESULTS = []


def report(test_name, passed, detail=""):
    status = "✓ PASS" if passed else "✗ FAIL"
    RESULTS.append((test_name, passed, detail))
    print(f"  {status}: {test_name}" + (f" — {detail}" if detail else ""))


def skip(test_name, detail=""):
    """A cleanly-skipped check counts as a pass (it does not fail the suite)."""
    RESULTS.append((test_name, True, f"SKIPPED — {detail}"))
    print(f"  ⊘ SKIP: {test_name}" + (f" — {detail}" if detail else ""))


# ── Minimal API helpers (urllib — no extra pip dependency) ────────────────────
def api(method, path, body=None, timeout=8):
    url = f"{SERVERS_API}{path}"
    data = json.dumps(body).encode('utf-8') if body is not None else None
    req = urllib.request.Request(url, data=data, method=method)
    req.add_header('Content-Type', 'application/json; charset=utf-8')
    with urllib.request.urlopen(req, timeout=timeout) as resp:
        raw = resp.read().decode('utf-8') or '{}'
        return resp.status, json.loads(raw) if raw.strip() else {}


def extract_id(body):
    for key in ('ID', 'id'):
        if isinstance(body, dict) and key in body:
            return body[key]
    data = body.get('Data') or body.get('data') if isinstance(body, dict) else None
    if isinstance(data, dict):
        return data.get('ID') or data.get('id')
    return None


def backends_reachable():
    try:
        status, _ = api('GET', '/api/v1/servers/types', timeout=5)
        return 200 <= status < 500
    except Exception:
        return False


def create_s3_server(name, secret=DUMMY_SECRET_KEY):
    status, body = api('POST', '/api/v1/servers', {
        'Name': name,
        'ServerType': 's3',
        'Direction': 'Input',
        'Host': MINIO_HOST,
        'Port': MINIO_PORT,
        'ConnectionTimeoutSeconds': 30,
        'RetryCount': 3,
        'TypeSpecificConfig': {
            'AccessKey': DUMMY_ACCESS_KEY,
            'SecretKey': secret,
            'Bucket': DUMMY_BUCKET,
            'Region': 'us-east-1',
            'ForcePathStyle': True,
            'UseHttp': True,
        },
    })
    return status, extract_id(body)


def delete_server(server_id):
    if not server_id:
        return
    try:
        api('DELETE', f'/api/v1/servers/{server_id}')
    except Exception:
        pass


# ── UI helpers ────────────────────────────────────────────────────────────────
def open_create_modal(page):
    """Navigate to admin settings, open the Input Servers create-server modal,
    and select ServerType = s3. Returns True on success, False if controls absent."""
    page.goto(f"{BASE_URL}/admin/settings", wait_until='networkidle')
    page.wait_for_timeout(800)

    # Best-effort: click the servers tab if present.
    page.evaluate("""() => {
        const el = document.querySelector('[id$="-tab-servers"]');
        if (el) el.dispatchEvent(new MouseEvent('click', { bubbles: true }));
    }""")
    page.wait_for_timeout(500)

    add = page.get_by_role('button', name=re.compile(r'(הוסף שרת|צור שרת|Add Server|Create Server)', re.I)).first
    try:
        if not add.is_visible(timeout=5000):
            return False
    except PWTimeout:
        return False
    add.click()
    page.wait_for_timeout(500)

    # Pick ServerType = s3.
    type_select = page.locator('.ant-modal .ant-select').filter(has=page.locator('input#ServerType'))
    type_select.click()
    page.wait_for_selector('.ant-select-dropdown:not(.ant-select-dropdown-hidden)', timeout=5000)
    page.locator('.ant-select-item-option').filter(has_text=re.compile(r's3|minio', re.I)).first.click()
    page.wait_for_timeout(500)
    return page.locator('input#AccessKey').is_visible()


def recon_dump(page):
    print("\n  --- RECON: resolved S3 modal selectors ---")
    for sel in ['#AccessKey', '#SecretKey', '#Bucket', '#Region', '#UsePathStyle', '#UseHttp']:
        loc = page.locator(f'input{sel}')
        cnt = loc.count()
        attrs = ''
        if cnt:
            el = loc.first
            attrs = f"type={el.get_attribute('type')} class={el.get_attribute('class')}"
        print(f"    input{sel}: count={cnt} {attrs}")


# ══════════════════════════════════════════════════════════════════════════════
def main():
    reachable = backends_reachable()

    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        page = browser.new_page(viewport={"width": 1400, "height": 900})

        print("=" * 64)
        print(" S3 / MINIO SERVER FORM — COMPREHENSIVE TEST SUITE")
        print("=" * 64)
        if not reachable:
            print("  (backends/MinIO unreachable — live-dependent groups will skip cleanly)")

        # ──────────────────────────────────────────────────────────────────────
        # GROUP 1: Secret masking (DOM)
        # ──────────────────────────────────────────────────────────────────────
        print("\n--- Group 1: Secret masking (DOM) ---")
        if not reachable:
            skip("T1.1 Secret Key input is masked (type=password)", "frontend/API unreachable")
            skip("T1.2 typed secret absent from plaintext attributes", "frontend/API unreachable")
        else:
            opened = open_create_modal(page)
            if not opened:
                skip("T1.1 Secret Key input is masked (type=password)", "create-server modal not found")
                skip("T1.2 typed secret absent from plaintext attributes", "create-server modal not found")
            else:
                recon_dump(page)
                secret = page.locator('input#SecretKey')
                masked = secret.get_attribute('type') == 'password'
                report("T1.1 Secret Key input is masked (type=password)", masked,
                       f"type={secret.get_attribute('type')}")

                # Type a secret, then assert it is not exposed in any plaintext attribute.
                secret.fill(DUMMY_SECRET_KEY)
                page.wait_for_timeout(200)
                leaked = False
                leaked_attr = ''
                for attr in ['value', 'placeholder', 'aria-label', 'aria-describedby', 'title']:
                    val = secret.get_attribute(attr) or ''
                    if DUMMY_SECRET_KEY in val:
                        leaked, leaked_attr = True, attr
                        break
                # Also check the rendered outerHTML does not echo the secret in plaintext.
                outer = secret.evaluate("el => el.outerHTML")
                if DUMMY_SECRET_KEY in outer:
                    leaked, leaked_attr = True, 'outerHTML'
                report("T1.2 typed secret absent from plaintext attributes", not leaked,
                       f"leaked in {leaked_attr}" if leaked else "no plaintext exposure")

        # ──────────────────────────────────────────────────────────────────────
        # GROUP 2: Edit keeps the stored secret on blank
        # ──────────────────────────────────────────────────────────────────────
        print("\n--- Group 2: Edit keeps stored secret on blank ---")
        if not reachable:
            skip("T2.1 blank-edit preserves stored secret (API)", "backends unreachable")
        else:
            name = f"webapp-S3-keep-{int(time.time())}"
            server_id = None
            try:
                status, server_id = create_s3_server(name)
                created_ok = status < 300 and server_id
                if not created_ok:
                    skip("T2.1 blank-edit preserves stored secret (API)", f"create failed status={status}")
                else:
                    # Re-fetch and confirm the API masks the secret (write-only).
                    _, got = api('GET', f'/api/v1/servers/{server_id}')
                    cfg = (got.get('TypeSpecificConfig') or
                           (got.get('Data') or {}).get('TypeSpecificConfig') or {})
                    returned_secret = cfg.get('SecretKey', '')
                    secret_not_echoed = returned_secret in ('', None, MASKED_SENTINEL)

                    # Update WITHOUT a real secret (send the masked sentinel — what the
                    # UI posts when the admin leaves the field untouched on edit).
                    upd_status, _ = api('PUT', f'/api/v1/servers/{server_id}', {
                        'Name': name,
                        'ServerType': 's3',
                        'Direction': 'Input',
                        'IsActive': True,
                        'Host': MINIO_HOST,
                        'Port': MINIO_PORT,
                        'ConnectionTimeoutSeconds': 30,
                        'RetryCount': 3,
                        'TypeSpecificConfig': {
                            'AccessKey': DUMMY_ACCESS_KEY,
                            'SecretKey': MASKED_SENTINEL,  # sentinel → keep existing
                            'Bucket': DUMMY_BUCKET,
                            'Region': 'us-east-1',
                            'ForcePathStyle': True,
                            'UseHttp': True,
                        },
                    })
                    # Re-fetch — the stored secret must NOT have been blanked.
                    _, after = api('GET', f'/api/v1/servers/{server_id}')
                    after_cfg = (after.get('TypeSpecificConfig') or
                                 (after.get('Data') or {}).get('TypeSpecificConfig') or {})
                    after_secret = after_cfg.get('SecretKey', '')
                    # The API still masks/keeps it (not an empty string overwrite).
                    not_blanked = after_secret not in ('',) and upd_status < 300
                    report("T2.1 blank-edit preserves stored secret (API)",
                           secret_not_echoed and not_blanked,
                           f"echoed='{returned_secret}' after='{after_secret}' put={upd_status}")
            finally:
                delete_server(server_id)

        # ──────────────────────────────────────────────────────────────────────
        # GROUP 3: Cancel discards typed credentials
        # ──────────────────────────────────────────────────────────────────────
        print("\n--- Group 3: Cancel discards credentials ---")
        if not reachable:
            skip("T3.1 Cancel discards typed credentials", "frontend unreachable")
        else:
            opened = open_create_modal(page)
            if not opened:
                skip("T3.1 Cancel discards typed credentials", "create-server modal not found")
            else:
                page.locator('input#AccessKey').fill(DUMMY_ACCESS_KEY)
                page.locator('input#SecretKey').fill(DUMMY_SECRET_KEY)
                page.wait_for_timeout(200)
                # Cancel the modal.
                page.locator('.ant-modal-footer .ant-btn:not(.ant-btn-primary)').first.click()
                page.wait_for_timeout(500)
                # Reopen and assert the fields are empty (destroyOnClose → fresh form).
                reopened = open_create_modal(page)
                if not reopened:
                    skip("T3.1 Cancel discards typed credentials", "modal did not reopen")
                else:
                    access_val = page.locator('input#AccessKey').input_value()
                    secret_val = page.locator('input#SecretKey').input_value()
                    discarded = access_val == '' and secret_val == ''
                    report("T3.1 Cancel discards typed credentials", discarded,
                           f"AccessKey='{access_val}' SecretKey='{secret_val}'")
                    # Close the modal to leave a clean state.
                    page.locator('.ant-modal-footer .ant-btn:not(.ant-btn-primary)').first.click()
                    page.wait_for_timeout(300)

        # ──────────────────────────────────────────────────────────────────────
        # GROUP 4: Test-Connection messaging
        # ──────────────────────────────────────────────────────────────────────
        print("\n--- Group 4: Test-Connection messaging ---")
        if not reachable:
            skip("T4.1 Test-Connection success messaging", "backends/MinIO unreachable")
            skip("T4.2 failure never shows IAM-credentials regression", "backends/MinIO unreachable")
        else:
            # T4.2 — failure path: bad secret must produce a clear error that is
            # NOT the regression string (the bug this phase fixes).
            bad_name = f"webapp-S3-bad-{int(time.time())}"
            bad_id = None
            try:
                status, bad_id = create_s3_server(bad_name, secret='definitely-wrong-secret')
                if status < 300 and bad_id:
                    try:
                        st, res = api('POST', f'/api/v1/servers/{bad_id}/test-connection', timeout=20)
                        msg = json.dumps(res)
                    except (urllib.error.HTTPError, urllib.error.URLError, Exception) as e:
                        st, msg = 0, str(e)
                    if st >= 500:
                        skip("T4.2 failure never shows IAM-credentials regression",
                             f"test-connection {st} — MinIO live run deferred to 34-06")
                    else:
                        report("T4.2 failure never shows IAM-credentials regression",
                               REGRESSION_STRING not in msg,
                               f"resp[:120]={msg[:120]}")
                else:
                    skip("T4.2 failure never shows IAM-credentials regression",
                         f"create failed status={status}")
            finally:
                delete_server(bad_id)

            # T4.1 — success path: needs live MinIO. Probe; skip if unreachable.
            good_name = f"webapp-S3-good-{int(time.time())}"
            good_id = None
            try:
                status, good_id = create_s3_server(good_name)
                if status < 300 and good_id:
                    try:
                        st, res = api('POST', f'/api/v1/servers/{good_id}/test-connection', timeout=20)
                    except Exception as e:
                        st, res = 500, {'error': str(e)}
                    if st >= 500:
                        skip("T4.1 Test-Connection success messaging",
                             f"test-connection {st} — MinIO live run deferred to 34-06")
                    else:
                        success = res.get('Success', res.get('success', (res.get('Data') or {}).get('Success')))
                        if success is True:
                            report("T4.1 Test-Connection success messaging", True, "Success=true")
                        else:
                            # MinIO not actually provisioned in this session — skip, not fail.
                            skip("T4.1 Test-Connection success messaging",
                                 f"Success!=true (MinIO not provisioned) — deferred to 34-06")
                else:
                    skip("T4.1 Test-Connection success messaging", f"create failed status={status}")
            finally:
                delete_server(good_id)

        # ──────────────────────────────────────────────────────────────────────
        # GROUP 5: Tooltip / help coverage
        # ──────────────────────────────────────────────────────────────────────
        print("\n--- Group 5: Tooltip / help coverage ---")
        if not reachable:
            skip("T5.1 S3 field labels surface help/label text", "frontend unreachable")
        else:
            opened = open_create_modal(page)
            if not opened:
                skip("T5.1 S3 field labels surface help/label text", "create-server modal not found")
            else:
                # Each S3 field renders a non-empty <label> (in-UI documentation of the
                # new fields). Hover the help icon if present to surface a tooltip.
                labels_ok = True
                detail_bits = []
                for field in ['AccessKey', 'SecretKey', 'Bucket', 'Region']:
                    item = page.locator('.ant-modal .ant-form-item').filter(
                        has=page.locator(f'input#{field}, [id="{field}"]'))
                    label = item.locator('.ant-form-item-label label').first
                    txt = (label.text_content() or '').strip() if label.count() else ''
                    detail_bits.append(f"{field}:'{txt[:20]}'")
                    if not txt:
                        labels_ok = False
                report("T5.1 S3 field labels surface help/label text", labels_ok,
                       " ".join(detail_bits))

                # Optional: a tooltip/help-icon hover surfaces .ant-tooltip-inner.
                help_icon = page.locator('.ant-modal .anticon-question-circle, .ant-modal .anticon-info-circle').first
                if help_icon.count() and help_icon.is_visible():
                    help_icon.hover()
                    page.wait_for_timeout(500)
                    tip = page.locator('.ant-tooltip-inner')
                    tip_txt = tip.text_content() if tip.is_visible() else ''
                    report("T5.2 help icon surfaces tooltip text", bool(tip_txt and tip_txt.strip()),
                           f"tooltip='{(tip_txt or '')[:40]}'")
                else:
                    skip("T5.2 help icon surfaces tooltip text", "no help icon in modal (labels suffice)")

        browser.close()

    # ── Summary ───────────────────────────────────────────────────────────────
    print("\n" + "=" * 64)
    print(" TEST RESULTS SUMMARY")
    print("=" * 64)
    passed = sum(1 for _, ok, _ in RESULTS if ok)
    failed = sum(1 for _, ok, _ in RESULTS if not ok)
    total = len(RESULTS)
    for name, ok, detail in RESULTS:
        mark = "✓" if ok else "✗"
        print(f"  {mark} {name}" + (f" — {detail}" if detail else ""))
    print(f"\n  Total: {total} | Passed/Skipped: {passed} | Failed: {failed}")
    if total:
        print(f"  Pass rate: {passed / total * 100:.0f}%")
    print("=" * 64)

    sys.exit(1 if failed > 0 else 0)


if __name__ == '__main__':
    main()
