/**
 * E2E Validation report generator.
 * Adapted from MatrixReporter pattern for E2E validation test suites.
 * Collects results across spec files via file-based persistence
 * and produces a markdown summary report.
 *
 * Output: src/Frontend/test-results/E2E-VALIDATION-REPORT.md
 */
import * as fs from 'fs';
import * as path from 'path';

/** Directory where per-spec-file result fragments are persisted */
const RESULTS_DIR = path.resolve(__dirname, '..', '..', '..', '..', 'test-results', '.e2e-validation-results');

export interface E2ETestResult {
  suite: string;       // 'pipeline-flow' | 'negative' | 'ui-workflow' | 'ui-monitoring' | 'cross-feature' | 'existing-backend' | 'existing-playwright'
  testName: string;
  passed: boolean;
  error?: string;
  durationMs?: number;
  category?: string;   // 'protocol' | 'format' | 'ui' | 'backend' | 'pipeline'
}

export class E2EValidationReporter {
  private results: E2ETestResult[] = [];
  private persistenceTag: string | null = null;

  /**
   * Enable automatic file-based persistence for this reporter instance.
   * Every addResult call will append to a JSON file identified by the tag.
   */
  enablePersistence(tag: string): void {
    this.persistenceTag = tag;
    if (!fs.existsSync(RESULTS_DIR)) {
      fs.mkdirSync(RESULTS_DIR, { recursive: true });
    }
  }

  /**
   * Add a test result and auto-persist if persistence is enabled.
   */
  addResult(result: E2ETestResult): void {
    this.results.push(result);
    if (this.persistenceTag) {
      this.appendResultToDisk(result);
    }
  }

  /**
   * Load all result fragment files from the persistence directory.
   * Used by teardown to collect results across all spec files.
   */
  loadAllPersistedResults(): void {
    if (!fs.existsSync(RESULTS_DIR)) return;
    const files = fs.readdirSync(RESULTS_DIR).filter(f => f.endsWith('.json'));
    for (const file of files) {
      const content = fs.readFileSync(path.join(RESULTS_DIR, file), 'utf-8');
      try {
        const loaded: E2ETestResult[] = JSON.parse(content);
        this.results.push(...loaded);
      } catch { /* skip malformed fragments */ }
    }
  }

  /**
   * Clean up persisted result fragment files.
   */
  static cleanPersistedResults(): void {
    if (!fs.existsSync(RESULTS_DIR)) return;
    const files = fs.readdirSync(RESULTS_DIR).filter(f => f.endsWith('.json'));
    for (const file of files) {
      fs.unlinkSync(path.join(RESULTS_DIR, file));
    }
  }

  /**
   * Generate a markdown report of all collected E2E validation results.
   */
  generateMarkdown(): string {
    const lines: string[] = [];
    const timestamp = new Date().toISOString();
    lines.push('# E2E Validation Report');
    lines.push('');
    lines.push(`**Generated:** ${timestamp}`);
    lines.push(`**Total Tests:** ${this.results.length}`);
    const passed = this.results.filter(r => r.passed).length;
    const failed = this.results.filter(r => !r.passed).length;
    lines.push(`**Passed:** ${passed} | **Failed:** ${failed}`);
    lines.push('');

    // Group by suite
    const suites = [...new Set(this.results.map(r => r.suite))];
    lines.push('## Results by Suite');
    lines.push('');
    lines.push('| Suite | Test | Status | Duration | Error |');
    lines.push('|-------|------|--------|----------|-------|');
    for (const suite of suites) {
      const suiteResults = this.results.filter(r => r.suite === suite);
      for (const r of suiteResults) {
        const status = r.passed ? 'PASS' : 'FAIL';
        const dur = r.durationMs ? `${Math.round(r.durationMs / 1000)}s` : '-';
        const err = r.error ? r.error.substring(0, 80) : '-';
        lines.push(`| ${suite} | ${r.testName} | ${status} | ${dur} | ${err} |`);
      }
    }

    lines.push('');
    lines.push('## Summary by Suite');
    lines.push('');
    lines.push('| Suite | Passed | Failed | Total |');
    lines.push('|-------|--------|--------|-------|');
    for (const suite of suites) {
      const sr = this.results.filter(r => r.suite === suite);
      const sp = sr.filter(r => r.passed).length;
      const sf = sr.filter(r => !r.passed).length;
      lines.push(`| ${suite} | ${sp} | ${sf} | ${sr.length} |`);
    }

    if (failed > 0) {
      lines.push('');
      lines.push('## Failures');
      lines.push('');
      for (const r of this.results.filter(r => !r.passed)) {
        lines.push(`- **${r.suite}** / ${r.testName}: ${r.error || 'Unknown'}`);
      }
    }

    lines.push('');
    lines.push('---');
    lines.push(`*Report generated by E2EValidationReporter at ${timestamp}*`);
    return lines.join('\n');
  }

  /**
   * Write the report to disk. Returns the output file path.
   */
  writeReport(outputPath?: string): string {
    const filePath = outputPath || path.resolve(__dirname, '..', '..', '..', '..', 'test-results', 'E2E-VALIDATION-REPORT.md');
    const dir = path.dirname(filePath);
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(filePath, this.generateMarkdown(), 'utf-8');
    console.log(`[validation-reporter] Report written to: ${filePath}`);
    return filePath;
  }

  private appendResultToDisk(result: E2ETestResult): void {
    if (!this.persistenceTag) return;
    const filePath = path.join(RESULTS_DIR, `${this.persistenceTag}.json`);
    let existing: E2ETestResult[] = [];
    if (fs.existsSync(filePath)) {
      try { existing = JSON.parse(fs.readFileSync(filePath, 'utf-8')); } catch { /* reset */ }
    }
    existing.push(result);
    fs.writeFileSync(filePath, JSON.stringify(existing, null, 2), 'utf-8');
  }
}

/**
 * Singleton instance for cross-file accumulation.
 * Import this in spec files and call enablePersistence() in beforeAll().
 */
export const e2eReporter = new E2EValidationReporter();
