apiVersion: batch/v1
kind: Job
metadata:
  name: demo-data-generator
  namespace: ez-platform
  labels:
    app: demo-data-generator
    component: tools
spec:
  ttlSecondsAfterFinished: 300
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: demo-data-generator
    spec:
      restartPolicy: Never
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: demo-data-generator
        image: ez-platform/demo-data-generator:v0.1.1-rc1
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
        args:
          - "--mongodb-connection=mongodb"
        env:
          - name: DOTNET_ENVIRONMENT
            value: "Production"
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 1Gi
