{{- if .Values.networkPolicies.enabled }}
{{- if .Values.networkPolicies.infrastructure.allowMongoDBAccess }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-services-to-mongodb
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "ez-platform.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app: mongodb
  ingress:
  - from:
    - podSelector:
        matchLabels:
          tier: backend
    ports:
    - port: 27017
      protocol: TCP
{{- end }}

{{- if .Values.networkPolicies.infrastructure.allowKafkaAccess }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-services-to-kafka
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "ez-platform.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app: kafka
  ingress:
  - from:
    - podSelector:
        matchLabels:
          tier: backend
    ports:
    - port: 9092
      protocol: TCP
    - port: 9094
      protocol: TCP
{{- end }}

{{- if .Values.networkPolicies.infrastructure.allowHazelcastAccess }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-services-to-hazelcast
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "ez-platform.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app: hazelcast
  ingress:
  - from:
    - podSelector:
        matchLabels:
          tier: backend
    ports:
    - port: 5701
      protocol: TCP
{{- end }}
{{- end }}
