{{- if and .Values.observability.grafana.enabled (not .Values.observability.grafana.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: grafana-credentials
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "ez-platform.labels" . | nindent 4 }}
    app: ezplatform-grafana
type: Opaque
data:
  {{- if .Values.observability.grafana.auth.adminPassword }}
  admin-password: {{ .Values.observability.grafana.auth.adminPassword | b64enc | quote }}
  {{- else }}
  admin-password: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
{{- end }}
