/**
 * Protocol x format matrix report generator.
 * Collects test results across protocol test files and produces
 * a markdown summary table.
 *
 * Output: src/Frontend/test-results/protocol-matrix-report.md
 */
import * as fs from 'fs';
import * as path from 'path';

export interface TestResult {
  protocol: string;
  format: string;
  operation: 'TestConnection' | 'List' | 'Read' | 'Write';
  passed: boolean;
  error?: string;
  durationMs?: number;
}

export class MatrixReporter {
  private results: TestResult[] = [];

  /**
   * Add a test result to the matrix
   */
  addResult(
    protocol: string,
    format: string,
    operation: 'TestConnection' | 'List' | 'Read' | 'Write',
    passed: boolean,
    error?: string,
    durationMs?: number
  ): void {
    this.results.push({ protocol, format, operation, passed, error, durationMs });
  }

  /**
   * Get all collected results
   */
  getResults(): TestResult[] {
    return [...this.results];
  }

  /**
   * Generate a markdown report of the protocol x format matrix
   */
  generateMarkdown(): string {
    const lines: string[] = [];
    const timestamp = new Date().toISOString();

    lines.push('# Protocol x Format Test Matrix Report');
    lines.push('');
    lines.push(`**Generated:** ${timestamp}`);
    lines.push(`**Total Results:** ${this.results.length}`);
    lines.push('');

    // Build the main matrix table
    lines.push('## Results Matrix');
    lines.push('');
    lines.push('| Protocol | Format | TestConnection | List | Read | Write | Status |');
    lines.push('|----------|--------|----------------|------|------|-------|--------|');

    // Group by protocol + format
    const protocolFormats = this.getProtocolFormatGroups();

    let totalPass = 0;
    let totalFail = 0;

    for (const [key, ops] of protocolFormats) {
      const [protocol, format] = key.split('::');
      const testConn = this.formatOp(ops.get('TestConnection'));
      const list = this.formatOp(ops.get('List'));
      const read = this.formatOp(ops.get('Read'));
      const write = this.formatOp(ops.get('Write'));

      // Row status: any FAIL = FAIL
      const allOps = [ops.get('TestConnection'), ops.get('List'), ops.get('Read'), ops.get('Write')];
      const hasFailure = allOps.some((r) => r !== undefined && !r.passed);
      const hasAnyResult = allOps.some((r) => r !== undefined);
      const status = !hasAnyResult ? 'N/A' : hasFailure ? 'FAIL' : 'PASS';

      if (status === 'PASS') totalPass++;
      if (status === 'FAIL') totalFail++;

      lines.push(`| ${protocol} | ${format} | ${testConn} | ${list} | ${read} | ${write} | ${status} |`);
    }

    // Summary
    lines.push('');
    lines.push('## Summary');
    lines.push('');
    lines.push(`- **Passed:** ${totalPass}`);
    lines.push(`- **Failed:** ${totalFail}`);
    lines.push(`- **Total Combinations:** ${totalPass + totalFail}`);
    lines.push('');

    // Failures detail section
    const failures = this.results.filter((r) => !r.passed);
    if (failures.length > 0) {
      lines.push('## Failures');
      lines.push('');
      for (const f of failures) {
        lines.push(`- **${f.protocol}** / ${f.format} / ${f.operation}: ${f.error || 'Unknown error'}`);
      }
      lines.push('');
    }

    lines.push('---');
    lines.push(`*Report generated by protocol-matrix-reporter at ${timestamp}*`);

    return lines.join('\n');
  }

  /**
   * Write the report to disk
   */
  writeReport(outputPath?: string): string {
    const defaultPath = path.resolve(
      __dirname,
      '..',
      '..',
      '..',
      'test-results',
      'protocol-matrix-report.md'
    );
    const filePath = outputPath || defaultPath;

    // Ensure output directory exists
    const dir = path.dirname(filePath);
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }

    const content = this.generateMarkdown();
    fs.writeFileSync(filePath, content, 'utf-8');

    console.log(`[report-generator] Matrix report written to: ${filePath}`);
    return filePath;
  }

  /**
   * Reset all collected results
   */
  reset(): void {
    this.results = [];
  }

  // ===== Private helpers =====

  private getProtocolFormatGroups(): Map<string, Map<string, TestResult>> {
    const groups = new Map<string, Map<string, TestResult>>();

    for (const result of this.results) {
      const key = `${result.protocol}::${result.format}`;
      if (!groups.has(key)) {
        groups.set(key, new Map());
      }
      groups.get(key)!.set(result.operation, result);
    }

    return groups;
  }

  private formatOp(result: TestResult | undefined): string {
    if (!result) return 'N/A';
    return result.passed ? 'PASS' : 'FAIL';
  }
}

/**
 * Singleton instance for cross-file accumulation.
 * Protocol test files import this and add results during execution.
 * The global teardown writes the final report.
 */
export const matrixReporter = new MatrixReporter();
